-- MySQL Script generated by MySQL Workbench
-- 03/06/17 13:37:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Projekt_3_VT_Mult
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projekt_3_VT_Mult
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projekt_3_VT_Mult` DEFAULT CHARACTER SET utf8 ;
USE `Projekt_3_VT_Mult` ;

-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`class` (
  `className` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`className`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`user` (
  `userId` NVARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `role` ENUM('S', 'T') NOT NULL,
  `class_className` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_user_class1_idx` (`class_className` ASC),
  CONSTRAINT `fk_user_class1`
    FOREIGN KEY (`class_className`)
    REFERENCES `Projekt_3_VT_Mult`.`class` (`className`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`question` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`questionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`alternative` (
  `alternativeId` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `correct` TINYINT(1) NOT NULL,
  PRIMARY KEY (`alternativeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`user_answers_alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`user_answers_alternative` (
  `user_userId` NVARCHAR(45) NOT NULL,
  `alternative_alternativeId` INT NOT NULL,
  PRIMARY KEY (`user_userId`, `alternative_alternativeId`),
  INDEX `fk_user_has_alternative_alternative1_idx` (`alternative_alternativeId` ASC),
  INDEX `fk_user_has_alternative_user1_idx` (`user_userId` ASC),
  CONSTRAINT `fk_user_has_alternative_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `Projekt_3_VT_Mult`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_alternative_alternative1`
    FOREIGN KEY (`alternative_alternativeId`)
    REFERENCES `Projekt_3_VT_Mult`.`alternative` (`alternativeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`question_has_alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`question_has_alternative` (
  `question_questionId` INT NOT NULL,
  `alternative_alternativeId` INT NOT NULL,
  PRIMARY KEY (`question_questionId`, `alternative_alternativeId`),
  INDEX `fk_question_has_alternative_alternative1_idx` (`alternative_alternativeId` ASC),
  INDEX `fk_question_has_alternative_question1_idx` (`question_questionId` ASC),
  CONSTRAINT `fk_question_has_alternative_question1`
    FOREIGN KEY (`question_questionId`)
    REFERENCES `Projekt_3_VT_Mult`.`question` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_has_alternative_alternative1`
    FOREIGN KEY (`alternative_alternativeId`)
    REFERENCES `Projekt_3_VT_Mult`.`alternative` (`alternativeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`test` (
  `testId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `showResult` TINYINT(1) NOT NULL,
  PRIMARY KEY (`testId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_userId` VARCHAR(45) NOT NULL,
  `test_testId` INT NOT NULL,
  `grade` ENUM('IG', 'G', 'VG') NOT NULL,
  `points` INT(20) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Grade_user1_idx` (`user_userId` ASC),
  INDEX `fk_result_test1_idx` (`test_testId` ASC),
  CONSTRAINT `fk_Grade_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `Projekt_3_VT_Mult`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_test1`
    FOREIGN KEY (`test_testId`)
    REFERENCES `Projekt_3_VT_Mult`.`test` (`testId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`class_has_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`class_has_test` (
  `class_className` VARCHAR(45) NOT NULL,
  `test_testId` INT NOT NULL,
  PRIMARY KEY (`class_className`, `test_testId`),
  INDEX `fk_class_has_test_test1_idx` (`test_testId` ASC),
  INDEX `fk_class_has_test_class1_idx` (`class_className` ASC),
  CONSTRAINT `fk_class_has_test_class1`
    FOREIGN KEY (`class_className`)
    REFERENCES `Projekt_3_VT_Mult`.`class` (`className`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_has_test_test1`
    FOREIGN KEY (`test_testId`)
    REFERENCES `Projekt_3_VT_Mult`.`test` (`testId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projekt_3_VT_Mult`.`test_has_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projekt_3_VT_Mult`.`test_has_question` (
  `test_testId` INT NOT NULL,
  `question_questionId` INT NOT NULL,
  PRIMARY KEY (`test_testId`, `question_questionId`),
  INDEX `fk_test_has_question_question1_idx` (`question_questionId` ASC),
  INDEX `fk_test_has_question_test1_idx` (`test_testId` ASC),
  CONSTRAINT `fk_test_has_question_test1`
    FOREIGN KEY (`test_testId`)
    REFERENCES `Projekt_3_VT_Mult`.`test` (`testId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_has_question_question1`
    FOREIGN KEY (`question_questionId`)
    REFERENCES `Projekt_3_VT_Mult`.`question` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
